// src/components/ui/theme-switcher/ThemeSwitcher.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import {
  SwitchRoot,
  type SwitchRootEmits,
  type SwitchRootProps,
  SwitchThumb,
  useForwardPropsEmits,
} from "radix-vue";
import { computed, type HTMLAttributes } from "vue";
import { useDark, useToggle } from "@vueuse/core";
import { HalfMoon, SunLight } from "@iconoir/vue";

const props = defineProps<
  SwitchRootProps & { class?: HTMLAttributes["class"] }
>();

const emits = defineEmits<SwitchRootEmits>();

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props;

  return delegated;
});

const forwarded = useForwardPropsEmits(delegatedProps, emits);

const isDark = useDark({
  disableTransition: false,
});
const toggleTheme = useToggle(isDark);
</script>

<template>
  <SwitchRoot
    v-bind="forwarded"
    v-model:checked="isDark"
    v-on:update:checked="toggleTheme"
    :class="
      cn(
        'peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input',
        props.class
      )
    "
  >
    <SwitchThumb
      :class="
        cn(
          'pointer-events-none inline-flex justify-center items-center h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0'
        )
      "
    >
      <HalfMoon v-if="isDark" class="size-3 dark:text-white" />
      <SunLight v-else class="size-3 text-gray-500" />
    </SwitchThumb>
  </SwitchRoot>
</template>

// components/ThemeSwitcher.tsx
"use client";

import { useTheme } from "next-themes";
import { useEffect, useState } from "react";
import { Moon, Sun } from "./Icons";

export default function ThemeSwitcher() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme } = useTheme();
  const [isDark, setIsDark] = useState(theme === "dark");

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }

  return (
    <button
      type="button"
      role="switch"
      onClick={() => {
        setIsDark(!isDark);
        setTheme(theme === "dark" ? "light" : "dark");
      }}
      className={`flex h-6 w-12 shrink-0 cursor-pointer items-center rounded-full transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-offset-2 focus-visible:ring-offset-white disabled:cursor-not-allowed disabled:opacity-50  dark:focus-visible:ring-slate-300 dark:focus-visible:ring-offset-slate-950 dark:data-[state=checked]:bg-slate-50 dark:data-[state=unchecked]:bg-slate-800 ${
        isDark ? "bg-primary" : "bg-zinc-200"
      }`}
    >
      <span
        className={`relative left-1 p-[3px] bg-surface rounded-full align-middle transition duration-300 ${
          isDark && "translate-x-[22px]"
        }`}
      >
        {isDark ? (
          <Moon className="size-3 fill-primary" />
        ) : (
          <Sun className="size-3 fill-zinc-500" />
        )}
      </span>
    </button>
  );
}
